"""init

Revision ID: 2bf867d4045d
Revises: 
Create Date: 2023-05-31 14:48:37.385419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf867d4045d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('is_block', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'user_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('password',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('service_name', sa.String(length=512), nullable=False),
    sa.Column('encrypt_login', sa.String(length=1024), nullable=False),
    sa.Column('encrypt_password', sa.String(length=2048), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_name', 'encrypt_login', 'group_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password')
    op.drop_table('group')
    op.drop_table('user')
    # ### end Alembic commands ###
